### PR TITLE
feat: add script to generate CU calc record rules

### PR DESCRIPTION
**Pull request by Revolution1**

### CODE REVIEW

**Comment by yjhmelody** [comment]
Where is the spec for the CU json?

**Comment by Revolution1** [comment]
from rpc config @yjhmelody

**Comment by yjhmelody** [comment]
I means who make this spec? Is there a standard?
I have no related knowledge.

**Comment by koushiro** [comment]
> I means who make this spec? Is there a standard? I have no related knowledge.

https://www.notion.so/alt-research/CU-table-alt-subway-ff8307541b9e410b99c120c0f6005981
`rate_limit_weight` field of `rpc_configs/geth.yml`

**Review by koushiro — APPROVED** [review]

**Pull request merged**
